### ISSUE TITLE
500 Error when non-existent monkey type username is given

### ISSUE THREAD

**Issue by Nicholas-Chong** [LordExodius/monkey-widget#1]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/48600727/235304167-16d0ac3d-94fb-4a4c-a85b-1ea99a3f485b.png">

😱

**Comment by LordExodius** [comment]
thanks for bringing this up! I've added a placeholder for nonexistent monkeytype accounts in the most recent commit 😀 

(next time i'll open a PR or mention the issue in the commit message but i forgot)
